"""
report_generator.py
--------------------
Builds a downloadable Markdown executive report summarizing KPIs,
segments, and insights for the currently filtered view. Markdown is
used instead of PDF to keep the app dependency-light and reliably
deployable on Streamlit Community Cloud; users can convert/print the
.md file to PDF from any editor or browser if needed.
"""

from datetime import datetime
import pandas as pd


def generate_markdown_report(kpis: dict, exec_summary: str, insights: dict,
                              top_risk_accounts: pd.DataFrame, filters_applied: dict) -> str:
    now = datetime.now().strftime("%B %d, %Y %H:%M")

    filter_lines = []
    for label, values in filters_applied.items():
        if values:
            filter_lines.append(f"- **{label}**: {', '.join(map(str, values)) if isinstance(values, list) else values}")
    filter_block = "\n".join(filter_lines) if filter_lines else "- No filters applied (full dataset)"

    def bullets(items):
        return "\n".join(f"- {i}" for i in items) if items else "- No notable observations for this view."

    top_risk_table = "| Customer | Company | Plan | MRR | Health | Risk |\n|---|---|---|---|---|---|\n"
    for _, row in top_risk_accounts.head(10).iterrows():
        top_risk_table += (
            f"| {row['customer_id']} | {row['company_name']} | {row['plan']} | "
            f"${row['mrr']:,.0f} | {row['customer_health_score']:.0f} | {row['renewal_risk_score']:.0f} |\n"
        )

    report = f"""# Subscription Renewal & Expansion Analytics — Executive Report

*Generated {now}*

## Filters Applied
{filter_block}

## Executive Summary

{exec_summary}

## Key Performance Indicators

| Metric | Value |
|---|---|
| Monthly Recurring Revenue (MRR) | ${kpis['mrr']:,.0f} |
| Annual Recurring Revenue (ARR) | ${kpis['arr']:,.0f} |
| Net Revenue Retention (NRR) | {kpis['nrr']:.1f}% |
| Gross Revenue Retention (GRR) | {kpis['grr']:.1f}% |
| Renewal Rate | {kpis['renewal_rate']:.1f}% |
| Churn Rate | {kpis['churn_rate']:.1f}% |
| Avg. Customer Health Score | {kpis['customer_health']:.0f} / 100 |
| Expansion Revenue | ${kpis['expansion_revenue']:,.0f} |
| Contraction Revenue | ${kpis['contraction_revenue']:,.0f} |
| Revenue Leakage | ${kpis['revenue_leakage']:,.0f} |
| Avg. Customer Lifetime Value (CLV) | ${kpis['clv']:,.0f} |
| Avg. Revenue per Account (ARPA) | ${kpis['arpa']:,.0f} |
| Avg. Contract Value (ACV) | ${kpis['acv']:,.0f} |
| Accounts in View | {kpis['customer_count']:,} |

## Revenue Insights
{bullets(insights.get('revenue', []))}

## Churn Insights
{bullets(insights.get('churn', []))}

## Customer Health Insights
{bullets(insights.get('health', []))}

## Top 10 Highest-Risk Accounts (by Renewal Risk Score)

{top_risk_table}

---
*Report generated by the SaaS Subscription Renewal & Expansion Analytics platform.*
"""
    return report